name: Nix Flake
on:
  pull_request:
  push:

jobs:
  build-packages:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        package:
          - solc
          - hevm
          - hevmUnwrapped
          - jays
          - jshon
          - seth
          - dapp
          - ethsign
          - token
          - go-ethereum-unlimited
          - qrtx
          - qrtx-term
          - secp256k1
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: dapp
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix build --show-trace --print-build-logs .#${{ matrix.package }}
